### ISSUE TITLE
[Task][TencentCloud] Cost Analysis Support Tencent

### ISSUE THREAD

**Issue by lbsu** [galaxy-future/costpilot#4]
### **背景**
为 CostPilot 增加支持 腾讯云 账单分析所需的底层 openapi 对接。

### **任务**
-  完成 Tencent 的 QueryAccountBill 接口对接；
(代码入口：internal/providers/tencent/api.go)
- 完成相应的单元测试；
(代码入口：internal/providers/tencent/api_test.go)

### **技能要求和编程语言**
- 熟悉腾讯云 openapi 对接；
- Golang；

### **预期完成结果**
- 可通过 CostPilot 完成 腾讯云 账单分析；
- 有相对完整的单元测试用例；

### **关于 PR**
dev 分支为默认主分支， issue 完成后请向 test 分支提交 PR。

### **参考**
[CostPilot 任务对接指南](https://galaxy-future.feishu.cn/docx/K5q8doejCotnUnxG32jc6kuNnwe)

------
开发者可扫码添加官方助手，入群沟通 :)

![](https://www.galaxy-future.com/image/qr_cs_362e7.jpg)

**Comment by baiyutang** [comment]
I will try to finish this task. please assign to me.
